  language: ruby
  rvm:
    - 2.2.2
bundler_args: --jobs=2
script:
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
before_build:
  - rubocop
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
