  language: ruby
  rvm:
    - 2.2.2
  cache: bundler
bundler_args: --jobs=2
script:
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
  - bundle exec rubocop
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
