  language: ruby
  rvm:
    - 2.2.2
bundler_args: --jobs=2
script:
script:
  - bundle exec rake db:create
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
